name       : haskell-text
version    : 1.2.2.1
release    : 2
source     :
    - http://hackage.haskell.org/package/text-1.2.2.1/text-1.2.2.1.tar.gz : 1addb1bdf36293c996653c9a0a320b5491714495862d997a23fb1ecd41ff395b
license    : BSD-3-Clause
component  : programming
summary    : An efficient packed, immutable Unicode text type (both strict and lazy),
    with a powerful loop fusion optimization framework.
description: |
    An efficient packed, immutable Unicode text type (both strict and lazy), with a powerful loop fusion optimization framework.
builddeps  :
    - ghc
setup      : |
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc

build      : |
    ./Setup %JOBS% build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 text-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/text-$version.conf
