name       : haskell-text
version    : 1.2.3.0
release    : 6
source     :
    - https://hackage.haskell.org/package/text-1.2.3.0/text-1.2.3.0.tar.gz : 20e0b1627f613b32cc7f2d2e8dcc48a4a61938b24f3d14fb77cee694f0c9311a
license    : BSD-3-Clause
component  : programming.haskell
summary    : An efficient packed, immutable Unicode text type (both strict and lazy),
    with a powerful loop fusion optimization framework.
description: |
    An efficient packed, immutable Unicode text type (both strict and lazy), with a powerful loop fusion optimization framework.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
